---
title: 10 Savvy Hacks to Sounding Confident
author: Javier Ng
date: '2019-02-18'
categories: ["Thoughts", "Motivation"]
tags: ["Thoughts", "Motivation"]
image:
  caption: ''
  focal_point: ''
---

If confidence could be bottled, it would be an overnight sensation. Confidence is a trait we admire in others and lament the absence of in ourselves. But while some people may indeed just be born confident, it’s a skill the rest of us can acquire with practice and the right mindset.

As all the best performers and public speakers know, confidence is as much about appearance as it is about feeling it. So where better to start honing your confidence than with your voice — one of the most important tools you have, to give others a favorable impression?

As psychologist and author Larina Kase said: “True confidence is not thinking that you’ll get a great result. It’s knowing that you can handle any result.” Read on to learn 10 savvy hacks to sounding confident. These expert tips will prepare you for success in any professional or public-speaking situation.

1. Practice

The key to doing anything well is doing it often, and speech is no exception. When you’re nervous about a difficult conversation, such as asking your boss for a raise, or a scheduled talk in front of an audience, practice what you have to say beforehand. If possible, try using a real or stand-in microphone if you’ll be using one during the actual event. Recording yourself is also a good way to adjust your pacing and pauses wherever necessary. It also allows you to evaluate your voice for clarity and volume.

2. Don’t articulate a statement as a question

People ask questions when they’re searching for information or want approval for an idea or decision. While there’s nothing inherently wrong with either of those situations, both can make you sound vulnerable. To project your ideas with confidence, don’t let your tone creep upward at the end of a sentence. Maintain an even tone of voice and finish your statements with periods, not question marks.

3. Slow down

190 words per minute is the ideal rate of speech for public speaking. At this speed, your audience will feel less like you’re talking at them and more like you’re having a conversation with them over lunch. If you speak too slowly, you run the risk of putting your audience to sleep. Yet, if you talk too quickly, you may sound amateurish or nervous, like you’re trying to get it over with as fast as you can. Thus, 190 words per minute is the optimal pacing you should aim for.

4. Use your hands

The body language that accompanies your message is just as important as the words coming out of your mouth. Audiences perceive speakers to have more positive traits such as warmth and energy when they use a variety of gestures. While some physical gestures, such as fiddling with clothing or touching hair, can distract or convey a lack of confidence, gesturing with your hands when you speak is a great way to communicate your excitement and knowledge about the topic.

5. Throw away caveats and filler phrases

Do you ever begin your sentences with, “This is just my opinion,” “Sorry,” “I’m still working on this,” “Well,” “I mean,” or any number of other negative or useless prefaces? Most people do so as a matter of habit or nervousness, but caveats and fillers can damage the confident tone you’re trying to strike. Instead, say what you mean and nothing else. For example, “We should take this pitch in a different direction,” is much more persuasive than, “Well, I think we should take this pitch in a different direction, but I’m still trying to find out the best route to take.”

6. Stay hydrated

Professional singers have favorite pre-show beverages to soothe and prepare their vocal cords. And while you may not need to hit any octaves during your next conference call, hydration is equally important for speakers. When you hydrate your vocal cords, it keeps them moisturized and enhances the sound of your voice. Drink water regularly throughout the day for the best results.

7. Express gratitude

When a leader shows gratitude, it helps create a positive atmosphere. The display of gratitude conveys the message that all is well and moving in a forward direction. Thus, thanking coworkers and direct-reports for their contributions and achievements is another way to say the company is thriving and on track to do even better in the future. Start the conversation with a little gratitude, even a “Thanks for coming,” and you’ll convey confidence from the start.

8. Insert smiles into your speech

Have you heard the adage that smiles are contagious? Smiling not only makes your voice more pleasant to listen to, it also conveys confidence. You will appear friendly, approachable, and composed. That’s more than enough reason to grin the next time you give an important talk!

9. Use silence to your advantage

What’s your biggest public speaking fear? For many people, it’s silence. They worry about forgetting an important idea or losing their train of thought midway through a sentence. Speakers who try to engage their audiences with questions worry that no one will respond. But silence isn’t your enemy; it can actually be a powerful confidence-projecting tool. It is important to input in strategic pauses in your speech in order to give your audience the time to retain and understand your points. Additionally, the ability to live with silences, whether of your own making or the audience’s, makes you seem confident.

10. Maintain good posture

Holding your head high and rolling your shoulders back won’t just make you look confident; it will improve the sound of your voice as well. Having a good posture and breathing in and out through your abdomen, is how actors and other public speakers project their voices to resonate clearly throughout the space. So to maximize the power of your voice, sit, or stand up straight and take a deep breath.

